# permissions for end users to view suzannes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suzanne-viewer-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - suzannes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - suzannes/status
  verbs:
  - get
