# permissions for end users to edit suzannes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suzanne-editor-role
rules:
- apiGroups:
  - cache.example.com
  resources:
  - suzannes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - suzannes/status
  verbs:
  - get
